# Setup
title:        Amit Blog
tagline:      Welcome! I'm Amit Kumar, Android Engineer @Primebook. Electronics & Communicaion Engineering @IIT Roorkee.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Amit Kumar
  url:        https://amitkma.github.io 

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

#Others
markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-gist
  
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      slug: null
